package com.patrick.algorithms;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;

import java.util.List;
import java.util.Map;

/**
 * @author patrick
 * @date 2021/3/4 1:51 下午
 * @Des ddemo
 * 最簡單的事是堅持，最難的事還是堅持
 */
public class Demo1 {
    public static List getString1() {
        String a = "[{\n" +
                "\t\t\"id\": \"6035fc8ee18171d090ae6685\",\n" +
                "\t\t\"name\": \"浦发银行\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 225,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"name\": \"总行信息科技部\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 224,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"6035fc8ee18171d090ae6685\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5eba0562607f6f001208495e\",\n" +
                "\t\t\"name\": \"测试服务中心\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 17,\n" +
                "\t\t\"current_count\": 12,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5efaf88316a87400123bd6fe\",\n" +
                "\t\t\"name\": \"规划部门\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5eba0562607f6f001208495e\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-2-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5ef9dc173e129800123c04bb\",\n" +
                "\t\t\"name\": \"业务部门\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 5,\n" +
                "\t\t\"current_count\": 5,\n" +
                "\t\t\"parent_id\": \"5eba0562607f6f001208495e\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-2-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40b6\",\n" +
                "\t\t\"name\": \"总经理室\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40b8\",\n" +
                "\t\t\"name\": \"规划管理处\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40b9\",\n" +
                "\t\t\"name\": \"大数据应用中心 \",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40ba\",\n" +
                "\t\t\"name\": \"系统运维中心\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"name\": \"开发服务中心\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 206,\n" +
                "\t\t\"current_count\": 8,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40b5\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40bc\",\n" +
                "\t\t\"name\": \"公共渠道开发处\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c4\",\n" +
                "\t\t\"name\": \"公共渠道\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-1-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40bd\",\n" +
                "\t\t\"name\": \"核心平台开发处\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c5\",\n" +
                "\t\t\"name\": \"基础平台\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bd\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-2-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c6\",\n" +
                "\t\t\"name\": \"基础平台（架构借调）\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bd\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-2-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c7\",\n" +
                "\t\t\"name\": \"村镇银行\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bd\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-2-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40be\",\n" +
                "\t\t\"name\": \"创新实验室\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"name\": \"应用开发服务分中心(上海)\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 198,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"name\": \"互联网应用\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 198,\n" +
                "\t\t\"current_count\": 64,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5c81c56cd3e2a1986ce30aw1\",\n" +
                "\t\t\"name\": \"移动组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 3,\n" +
                "\t\t\"current_count\": 2,\n" +
                "\t\t\"parent_id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5cb97dee3358ba00077075ff\",\n" +
                "\t\t\"name\": \"统一收银台小组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 1,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"5c81c56cd3e2a1986ce30aw1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-7-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"name\": \"零售金融APP组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 7,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3e93f5606eeb000a22d322\",\n" +
                "\t\t\"name\": \"板块3-互联组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 1,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3e9411606eeb000a22d325\",\n" +
                "\t\t\"name\": \"板块6-APP组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 3,\n" +
                "\t\t\"current_count\": 3,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3e9405606eeb000a22d324\",\n" +
                "\t\t\"name\": \"板块5-公共组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 2,\n" +
                "\t\t\"current_count\": 2,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3e93ed606eeb000a22d321\",\n" +
                "\t\t\"name\": \"板块2-微生活组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3e9418606eeb000a22d326\",\n" +
                "\t\t\"name\": \"板块7-账户组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 1,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d6c84ce054583000aa4e9af\",\n" +
                "\t\t\"name\": \"板块8-生态组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-8\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5d3e93ce606eeb000a22d320\",\n" +
                "\t\t\"name\": \"板块1-财富组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f9a60899513dd000c0a1b4c\",\n" +
                "\t\t\"name\": \"板块9-蓉亿组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-9\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f9bc3479513dd000c0a1e68\",\n" +
                "\t\t\"name\": \"板块6-投资组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5d3ebdc2606eeb000a22d335\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-11-15\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"name\": \"零售金融组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 21,\n" +
                "\t\t\"current_count\": 9,\n" +
                "\t\t\"parent_id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f055809139e1d001256c8c3\",\n" +
                "\t\t\"name\": \"板块7-账户组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 1,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0683cd2449f60012c2321f\",\n" +
                "\t\t\"name\": \"板块8-生态组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-8\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0557de139e1d001256c8bf\",\n" +
                "\t\t\"name\": \"板块2-微生活组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 1,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0557e9139e1d001256c8c0\",\n" +
                "\t\t\"name\": \"板块5-公共组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 3,\n" +
                "\t\t\"current_count\": 3,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0557f1139e1d001256c8c1\",\n" +
                "\t\t\"name\": \"板块1-财富组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 7,\n" +
                "\t\t\"current_count\": 4,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0688f12449f60012c23221\",\n" +
                "\t\t\"name\": \"1组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 1,\n" +
                "\t\t\"current_count\": 1,\n" +
                "\t\t\"parent_id\": \"5f0557f1139e1d001256c8c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-1-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f082a0b9dae080012cf90aa\",\n" +
                "\t\t\"name\": \"2组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 2,\n" +
                "\t\t\"current_count\": 2,\n" +
                "\t\t\"parent_id\": \"5f0557f1139e1d001256c8c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-1-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0557cb139e1d001256c8bd\",\n" +
                "\t\t\"name\": \"板块6-APP组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f055800139e1d001256c8c2\",\n" +
                "\t\t\"name\": \"板块4-转账组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0557d5139e1d001256c8be\",\n" +
                "\t\t\"name\": \"板块3-互联组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5f055798139e1d001256c8bc\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5f0fe8dae22f9b0012603e9c\",\n" +
                "\t\t\"name\": \"一组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"5f0557d5139e1d001256c8be\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-1-3-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"123asdasb3241ad13adada13\",\n" +
                "\t\t\"name\": \"支付组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 3,\n" +
                "\t\t\"current_count\": 3,\n" +
                "\t\t\"parent_id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5c81c56cd3e2a1126ce301c4\",\n" +
                "\t\t\"name\": \"公司及PAD组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 4,\n" +
                "\t\t\"current_count\": 4,\n" +
                "\t\t\"parent_id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5c81c56cd3e2a1126ce3004b\",\n" +
                "\t\t\"name\": \"公共组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 96,\n" +
                "\t\t\"current_count\": 42,\n" +
                "\t\t\"parent_id\": \"5c81c4d0d3e2a1126ce30049\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"5e855f033288660012ece5ff\",\n" +
                "\t\t\"name\": \"效能\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 54,\n" +
                "\t\t\"current_count\": 54,\n" +
                "\t\t\"parent_id\": \"5c81c56cd3e2a1126ce3004b\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10-4-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40c8\",\n" +
                "\t\t\"name\": \"公共渠道\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40c9\",\n" +
                "\t\t\"name\": \"基础平台\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40ca\",\n" +
                "\t\t\"name\": \"基础平台（架构借调）\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40cb\",\n" +
                "\t\t\"name\": \"浦惠到家\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40cc\",\n" +
                "\t\t\"name\": \"个人业务\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40cd\",\n" +
                "\t\t\"name\": \"公司业务\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d99f7ed34b70eb40ce\",\n" +
                "\t\t\"name\": \"管理信息\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40cf\",\n" +
                "\t\t\"name\": \"信用卡业务\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-9\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d0\",\n" +
                "\t\t\"name\": \"中间业务\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bf\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-4-10\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c0\",\n" +
                "\t\t\"name\": \"应用开发服务分中心(合肥)\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d1\",\n" +
                "\t\t\"name\": \"合肥开发A\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c0\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-5-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d2\",\n" +
                "\t\t\"name\": \"合肥开发B\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c0\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-5-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d3\",\n" +
                "\t\t\"name\": \"合肥开发C\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c0\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-5-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d4\",\n" +
                "\t\t\"name\": \"合肥开发D\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c0\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-5-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"name\": \"应用开发服务分中心(成都)\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d5\",\n" +
                "\t\t\"name\": \"成都综合服务团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d6\",\n" +
                "\t\t\"name\": \"成都研发一团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d7\",\n" +
                "\t\t\"name\": \"成都研发二团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d8\",\n" +
                "\t\t\"name\": \"成都研发三团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40d9\",\n" +
                "\t\t\"name\": \"成都研发四团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40da\",\n" +
                "\t\t\"name\": \"成都研发五团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40db\",\n" +
                "\t\t\"name\": \"成都研发六团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40dc\",\n" +
                "\t\t\"name\": \"成都研发七团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-8\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40dd\",\n" +
                "\t\t\"name\": \"成都研发八团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-9\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40de\",\n" +
                "\t\t\"name\": \"成都研发九团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-10\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40df\",\n" +
                "\t\t\"name\": \"成都研发十团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-11\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40e0\",\n" +
                "\t\t\"name\": \"成都研发十一团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-12\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40e1\",\n" +
                "\t\t\"name\": \"成都研发十二团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-13\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40e2\",\n" +
                "\t\t\"name\": \"成都研发十三团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-14\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40e3\",\n" +
                "\t\t\"name\": \"成都研发十四团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-15\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716db9f7ed34b70eb40e4\",\n" +
                "\t\t\"name\": \"成都研发十五团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-16\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40e5\",\n" +
                "\t\t\"name\": \"成都研发十六团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-17\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40e6\",\n" +
                "\t\t\"name\": \"成都研发十七团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-18\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40e7\",\n" +
                "\t\t\"name\": \"成都研发十八团队\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c1\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-6-19\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"name\": \"应用开发服务分中心(武汉)\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40e8\",\n" +
                "\t\t\"name\": \"武汉公共研发组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40e9\",\n" +
                "\t\t\"name\": \"武汉手机二组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40ea\",\n" +
                "\t\t\"name\": \"武汉手机三组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40eb\",\n" +
                "\t\t\"name\": \"武汉手机六组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40ec\",\n" +
                "\t\t\"name\": \"武汉手机七组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40ed\",\n" +
                "\t\t\"name\": \"武汉手机八组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40ee\",\n" +
                "\t\t\"name\": \"武汉支付测试组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c2\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-7-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"name\": \"应用开发服务分中心(西安)\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40bb\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40ef\",\n" +
                "\t\t\"name\": \"西安第六板块\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-1\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f0\",\n" +
                "\t\t\"name\": \"西安第六板块（测试方向挂靠开发岗位）\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-2\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f1\",\n" +
                "\t\t\"name\": \"西安第六板块（安全方向挂靠开发岗位）\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-3\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f2\",\n" +
                "\t\t\"name\": \"西安管理信息三组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-4\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f3\",\n" +
                "\t\t\"name\": \"西安对公一组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-5\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f4\",\n" +
                "\t\t\"name\": \"西安对公二组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-6\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f5\",\n" +
                "\t\t\"name\": \"西安个人及中间\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-7\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f6\",\n" +
                "\t\t\"name\": \"西安管理信息一组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-8\"\n" +
                "\t}, {\n" +
                "\t\t\"id\": \"603716dc9f7ed34b70eb40f7\",\n" +
                "\t\t\"name\": \"西安管理信息二组\",\n" +
                "\t\t\"fullName\": \"\",\n" +
                "\t\t\"count\": 0,\n" +
                "\t\t\"current_count\": 0,\n" +
                "\t\t\"parent_id\": \"603716d89f7ed34b70eb40c3\",\n" +
                "\t\t\"status\": \"1\",\n" +
                "\t\t\"sortNum\": \"1-1-6-8-9\"\n" +
                "\t}]";
        JSONArray parse = JSON.parseArray(a);
        return parse;
    }
}
